### ISSUE TITLE
Fixing of file names on case-insensitive file systems fails with `Error: A file with the new name 'my-file-name.md' exists.`

### ISSUE THREAD

**Issue by universemaster** [mausworks/tidier#33]
[Apple file system (APFS)](https://support.apple.com/en-gb/guide/disk-utility/dsku19ed921c/19.0/mac/10.15) is configured (at least on my system) as case-insensitive, in the sense that HOMEWORK.md and homework.md are not allowed to coexist.

Thus, when I try to convert `My-File-Name.md` to the lower case equivalent, I get the error:

`Error: A file with the new name 'my-file-name.md' exists.`

I note the comments on tidier-core about the overwrite option but this is not available on the vscode extension that I am using.

**Comment by mausworks** [comment]
Hey, thanks a lot for your issue! I'll see what I can do to make this option available to set for the VSCode extension.

**Comment by mausworks** [comment]
Just as a note. On my MacBook pro that I use for work, I do not have this issue, the filesystem API in NodeJS does not return any file when I `stat` a file using the wrong casing. Super weird!

Regardless, I'm enabling "rename overwrites" by default for MacOS as well in the next release of the extension and CLI.

**Comment by mausworks** [comment]
This should all be fixed now, let me know if the problem still persists.
